(
step
  (
  if
    (
    not
      (
      or
        (
        if
          (
          eq
            (
            getMidpoint
            )
          8.6841201490812
          )
          (
          if
            (
            lt
              (
              getRange
              1
              )
            5.185157289620461
            )
            (
            pickUp
            )
            (
            setSpeed
            -0.1
            0.475
            )
          )
        )
        (
        if
          (
          lte
            (
            getMidpoint
            )
          3.2067589607460754
          )
          (
          setSpeed
          -0.09963357745222487
          0.3951756492342846
          )
        )
        (
        if
          (
          lte
            (
            getMidpoint
            )
          6.0
          )
          (
          setSpeed
          -0.08943720632472098
          0.22430513505579477
          )
        )
        (
        if
          (
          lt
            (
            getRange
            2
            )
          4.064414348206225
          )
          (
          eq
            (
            getRange
            11
            )
          8.58488025810811
          )
        )
        (
        if
          (
          lte
            (
            getRange
            5
            )
          5.185157289620461
          )
          (
          setSpeed
          -0.09340486199705927
          0.347108925541963
          )
        )
        (
        if
          (
          lt
            (
            getRange
            3
            )
          6.0
          )
          (
          setSpeed
          0.475
          -0.1
          )
        )
        (
        if
          (
          lt
            (
            getRange
            3
            )
          1.8360231066867438
          )
          (
          setSpeed
          0.30491374665986476
          -0.10682984423921285
          )
        )
        (
        if
          (
          lt
            (
            getRange
            15
            )
          1.1772083989190156
          )
          (
          setSpeed
          0.31088375231756715
          -0.057156704989294385
          )
        )
      )
    )
    (
    if
      (
      or
      )
      (
      setSpeed
      -0.1
      0.1
      )
      (
      if
        (
        or
          (
          and
            (
            not
              (
              setSpeed
              -0.08848133032354778
              0.3941208190428903
              )
            )
            (
            gt
              (
              getRange
              3
              )
            16.238091236523445
            )
          )
          (
          if
            (
            and
              (
              pickUp
              )
            )
            (
            setSpeed
            -0.14213414605106467
            0.7387120825722469
            )
          )
        )
        (
        setSpeed
        0.091475587055799
        -0.15612635575840197
        )
        (
        if
          (
          or
            (
            isCarrying
            )
            (
            lt
              (
              getWidth
              )
            12.506070866791072
            )
          )
          (
          setSpeed
          0.2
          0.2
          )
          (
          and
            (
            setSpeed
            0.05155557142493228
            -0.06930324013675715
            )
            (
            if
              (
              or
                (
                and
                )
                (
                and
                  (
                  isCarrying
                  )
                  (
                  lt
                    (
                    getMidpoint
                    )
                  5.787494109432693
                  )
                )
              )
              (
              setSpeed
              -0.07571027568550473
              0.11778680230999168
              )
              (
              if
                (
                or
                  (
                  if
                    (
                    not
                      (
                      or
                        (
                        if
                          (
                          eq
                            (
                            getRange
                            11
                            )
                          4.935823026569883
                          )
                          (
                          setSpeed
                          -0.13317217454121952
                          -0.26484403778124727
                          )
                        )
                        (
                        if
                          (
                          lt
                            (
                            getMidpoint
                            )
                          4.3608537368855025
                          )
                          (
                          setSpeed
                          -0.1431565002307138
                          0.3076021775603291
                          )
                        )
                        (
                        if
                          (
                          lte
                            (
                            getMidpoint
                            )
                          6.0
                          )
                          (
                          pickUp
                          )
                          (
                          setSpeed
                          -0.08943720632472098
                          0.22430513505579477
                          )
                        )
                        (
                        if
                          (
                          lt
                            (
                            getRange
                            12
                            )
                          2.963372354216652
                          )
                          (
                          eq
                            (
                            getRange
                            11
                            )
                          8.58488025810811
                          )
                        )
                        (
                        if
                          (
                          or
                            (
                            and
                              (
                              not
                                (
                                setSpeed
                                -0.1
                                0.475
                                )
                              )
                              (
                              gt
                                (
                                getRange
                                10
                                )
                              26.40710578718065
                              )
                            )
                            (
                            if
                              (
                              eq
                                (
                                getRange
                                15
                                )
                              6.0
                              )
                              (
                              setSpeed
                              -0.11136864405351887
                              0.5354234710691486
                              )
                              (
                              not
                                (
                                gt
                                  (
                                  getRange
                                  10
                                  )
                                0.0
                                )
                              )
                            )
                          )
                          (
                          setSpeed
                          -0.09340486199705927
                          0.347108925541963
                          )
                        )
                        (
                        if
                          (
                          lte
                            (
                            getRange
                            3
                            )
                          6.0
                          )
                          (
                          setSpeed
                          0.6295712984016936
                          -0.0613738464999143
                          )
                        )
                        (
                        if
                          (
                          lte
                            (
                            getWidth
                            )
                          6.0
                          )
                          (
                          setSpeed
                          0.569562541547058
                          -0.12811916156569322
                          )
                        )
                        (
                        if
                          (
                          lt
                            (
                            getRange
                            7
                            )
                          5.115622177292363
                          )
                          (
                          setSpeed
                          0.5219534643988518
                          -0.09123056281988157
                          )
                        )
                        (
                        if
                          (
                          lt
                            (
                            getRange
                            10
                            )
                          2.3850194730553045
                          )
                          (
                          setSpeed
                          0.31088375231756715
                          -0.057156704989294385
                          )
                        )
                      )
                    )
                    (
                    if
                      (
                      or
                        (
                        and
                          (
                          isCarrying
                          )
                          (
                          lt
                            (
                            getRange
                            5
                            )
                          2.4953834035360076
                          )
                        )
                      )
                      (
                      setSpeed
                      -0.1
                      0.1
                      )
                      (
                      if
                        (
                        or
                          (
                          and
                            (
                            setSpeed
                            -0.09340486199705927
                            0.347108925541963
                            )
                            (
                            gt
                              (
                              getRange
                              3
                              )
                            28.56590044490815
                            )
                          )
                          (
                          if
                            (
                            and
                              (
                              pickUp
                              )
                            )
                            (
                            setSpeed
                            -0.14213414605106467
                            0.7387120825722469
                            )
                          )
                        )
                        (
                        setSpeed
                        0.10534144696191697
                        -0.12493712737256223
                        )
                        (
                        if
                          (
                          or
                            (
                            isCarrying
                            )
                            (
                            lt
                              (
                              getWidth
                              )
                            13.201969490813436
                            )
                          )
                          (
                          setSpeed
                          0.1873829787444707
                          0.17028021741904636
                          )
                        )
                      )
                    )
                  )
                )
                (
                setSpeed
                0.06846807625685473
                -0.061368552053521624
                )
                (
                if
                  (
                  or
                    (
                    isCarrying
                    )
                  )
                  (
                  setSpeed
                  0.2
                  0.2
                  )
                  (
                  and
                    (
                    setSpeed
                    0.0
                    0.0
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)
